config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }

  authenticated :user do
    root 'profiles#setup', as: :authenticated_root
  end

  unauthenticated :user do
    root 'home#index', as: :unauthenticated_root
  end

  resources :welcome

  resource :profile, only: [:show, :edit, :update] do
    collection do
      get :setup
      post :update_setup
      get :setup_hobbies
      post :update_hobbies
      get :setup_dietary_restrictions
      post :update_dietary_restrictions
      get :setup_accessibility
      post :update_accessibility
    end
  end

  get 'profile/setup', to: 'profiles#setup', as: :profile_setup
  post 'profile/setup', to: 'profiles#update_setup'

  # Trip routes
  get 'trip/start_date', to: 'trips#start_date'
  post 'trip/save_start_date', to: 'trips#save_start_date'

  get 'trip/end_date', to: 'trips#end_date'
  post 'trip/save_end_date', to: 'trips#save_end_date'

  get 'trip/address', to: 'trips#address'
  post 'trip/save_address', to: 'trips#save_address'

  get 'trip/budget', to: 'trips#budget'
  post 'trip/save_budget', to: 'trips#save_budget'

  get 'trip/prompt', to: 'trips#show_prompt', as: :trip_prompt

  # Chatbot Routes
  get '/chatbot', to: 'pages#chatbot'
  post '/chatbot/submit', to: 'pages#submit_chat'
  get '/pages/step1', to: 'pages#step1'
  get '/pages/step2', to: 'pages#step2'

  get 'invalid_location', to: 'trips#invalid_location', as: 'invalid_location'
  get 'error_page', to: 'trips#error_page', as: 'error_page'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def setup
    # This action should render the form to input date of birth
  end

  def update_setup
    if current_user.update(date_of_birth: params[:dob])
      redirect_to setup_hobbies_profile_path
    else
      render :setup
    end
  end

  def setup_hobbies
    @hobbies = Hobby.all
    # This action should render the form to select hobbies
  end

  def update_hobbies
    current_user.hobbies = Hobby.where(name: params[:hobby_names])
    redirect_to setup_dietary_restrictions_profile_path
  end

  def setup_dietary_restrictions
    @dietary_restrictions = DietaryRestriction.all
    # This action should render the form to select dietary restrictions
  end

  def update_dietary_restrictions
    current_user.dietary_restrictions = DietaryRestriction.where(name: params[:dietary_restriction_ids])
    redirect_to setup_accessibility_profile_path
  end

  def setup_accessibility
    @accessibilities = Accessibility.all
    # This action should render the form to select accessibility needs
  end

  def update_accessibility
    current_user.accessibilities = Accessibility.where(name: params[:accessibility_ids])
    redirect_to welcome_index_path
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/setup.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, width=device-width">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" />
    <%= csrf_meta_tags %>
</head>
<body>
    <div class="interests">
        <%= form_with url: profile_setup_path, method: :post, id: "dob-form" do %>
        <img class="interests-child" alt="" src="/assets/Vector 5.svg">
        <div class="date-of-birth">Date Of Birth</div>
        <div class="please-enter-your">Please Enter Your Date Of Birth</div>
        <%= date_field_tag :dob, nil, class: "dob-field", placeholder: "dd-mm-yyyy" %>
        <div class="continue-14-wrapper" id="submit-btn">
            <b class="continue-14">CONTINUE 1/4</b>
        </div>
        <div class="interests-item"></div>
        <div class="interests-inner"></div>
        <% end %>
    </div>
</body>
</html>

<style type="text/css">
 .interests-child {
    position: absolute;
    top: 66px;
    left: 29px;
    width: 9.1px;
    height: 18.1px;
}
.date-of-birth {
    position: absolute;
    top: 106px;
    left: 54px;
    letter-spacing: 0.04em;
    line-height: 140%;
    font-weight: 600;
}
.please-enter-your {
    position: absolute;
    top: 170px;
    left: 63px;
    font-size: 13.19px;
    line-height: 17.06px;
    font-weight: 500;
    color: #c6c5c7;
}
.continue-14-wrapper {
    position: absolute;
    bottom: 50px;
    left: 50%;
    transform: translateX(-50%);
    border-radius: 67.18px;
    background-color: #ebecef;
    width: 312.4px;
    height: 50.4px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 18.14px;
    color: #828491;
    cursor: not-allowed;
}
.continue-14-wrapper.active {
    background-color: #ff6b6b;
    cursor: pointer;
}
.continue-14-wrapper.active .continue-14 {
    color: #fff;
}
.continue-14 {
    font-weight: 700;
}
.interests-item {
    position: absolute;
    top: 46px;
    left: 0px;
    background-color: #d9d9d9;
    width: 393px;
    height: 4px;
}
.interests-inner {
    position: absolute;
    top: 46px;
    left: 0px;
    background-color: #ea4080;
    width: 247px;
    height: 4px;
}
.rectangle-div {
    position: absolute;
    top: 244px;
    left: 21px;
    border-radius: 14px;
    background-color: #f7f7f9;
    border: 1px solid rgba(0, 0, 0, 0.5);
    box-sizing: border-box;
    width: 335px;
    height: 56px;
}
.dd-mm-yy {
    position: absolute;
    top: 260px;
    left: 32px;
    font-size: 19.1px;
    color: #000;
    text-align: center;
    opacity: 0.6;
}
.interests {
    width: 100%;
    position: relative;
    background-color: #fff;
    height: 852px;
    text-align: left;
    font-size: 38.29px;
    color: #010001;
    font-family: Inter;
}
.dob-field {
    position: absolute;
    top: 244px;
    left: 21px;
    width: 335px;
    height: 56px;
    padding: 10px;
    font-size: 19.1px;
    border: 1px solid rgba(0, 0, 0, 0.5);
    border-radius: 14px;
    background-color: #f7f7f9;
    box-sizing: border-box;
    text-align: left;
    color: #000;
    opacity: 0.6;
}


</style>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        const dobField = document.querySelector(".dob-field");
        const submitBtn = document.getElementById("submit-btn");
        const form = document.getElementById("dob-form");

        dobField.addEventListener("input", function() {
            const dob = dobField.value;
            const today = new Date();
            const dobDate = new Date(dob);

            let age = today.getFullYear() - dobDate.getFullYear();
            const monthDiff = today.getMonth() - dobDate.getMonth();
            const dayDiff = today.getDate() - dobDate.getDate();

            if (monthDiff < 0 || (monthDiff === 0 && dayDiff < 0)) {
                age--;
            }

            if (dob && dobDate <= today && age >= 18) {
                submitBtn.classList.add("active");
            } else {
                submitBtn.classList.remove("active");
            }
        });

        submitBtn.addEventListener("click", function(event) {
            if (!submitBtn.classList.contains("active")) {
                event.preventDefault();
                return;
            }

            const dob = dobField.value;
            const dobParts = dob.split("-");
            const formattedDob = `${dobParts[2]}-${dobParts[1]}-${dobParts[0]}`;

            fetch('http://localhost:4567/receive_data', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                },
                body: JSON.stringify({ 
                user_id: <%= current_user.id %>,  // Add user_id here
                dob: formattedDob 
            })
            })
            .then(response => response.json())
            .then(data => {
                console.log('Success:', data);
                form.submit();
            })
            .catch((error) => {
                console.error('Error:', error);
            });
        });
    });
</script>

app/views/profiles/setup_accessibility.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, width=device-width">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700&display=swap" />
  <style type="text/css">
    .wheel-chair-wrapper {
      border-radius: 100px;
      border: 2px solid #dee0e7;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 6px 12px;
      margin: 5px;
      cursor: pointer;
      transition: background-color 0.3s, border-color 0.3s;
      font-size: 14px;
      box-sizing: border-box;
      text-align: center;
    }
    .wheel-chair-wrapper.selected {
      background-color: #ea5b6e;
      border-color: #ea5b6e;
      color: #fff;
    }
    .interests-child {
      position: absolute;
      top: 66px;
      left: 29px;
      width: 9.1px;
      height: 18.1px;
    }
    .frame-parent {
      position: absolute;
      top: 232px;
      left: 45px;
      display: flex;
      flex-wrap: wrap;
      align-items: flex-start;
      justify-content: flex-start;
      gap: 10px;
      width: calc(100% - 90px);
      max-height: 400px;
      overflow-y: auto;
      padding-right: 10px;
    }
    .accessbility-issue {
      position: absolute;
      top: 106px;
      left: 50%;
      transform: translateX(-50%);
      font-size: 38.29px;
      letter-spacing: 0.04em;
      line-height: 140%;
      font-weight: 600;
      color: #010001;
      text-align: center;
      width: calc(100% - 126px);
    }
    .please-choose-all {
      position: absolute;
      top: 170px;
      left: 50%;
      transform: translateX(-50%);
      font-size: 13.19px;
      line-height: 17.06px;
      font-weight: 500;
      color: #c6c5c7;
      text-align: center;
    }
    .continue-44-wrapper {
      position: absolute;
      top: 750px;
      left: 50%;
      transform: translateX(-50%);
      border-radius: 67.18px;
      background-color: #ebecef;
      width: 312.4px;
      height: 50.4px;
      overflow: hidden;
      font-size: 18.14px;
      color: #828491;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: not-allowed; /* Initially disabled */
    }
    .continue-44-wrapper.active {
      background-color: #ea5b6e;
      color: #fff;
      cursor: pointer;
    }
    .interests-item {
      position: absolute;
      top: 46px;
      left: 0px;
      background-color: #d9d9d9;
      width: 393px;
      height: 4px;
    }
    .interests-inner {
      position: absolute;
      top: 46px;
      left: 0px;
      background-color: #ea4080;
      width: 247px;
      height: 4px;
    }
    .interests {
      width: 100%;
      position: relative;
      background-color: #fff;
      height: 852px;
      text-align: left;
      font-size: 14.98px;
      color: #bfc3cf;
      font-family: Inter;
    }
  </style>
</head>
<body>
  <div class="interests">
    <%= form_with url: update_accessibility_profile_path, method: :post do %>
    <div class="frame-parent">
      <% @accessibilities.each do |accessibility| %>
      <div class="wheel-chair-wrapper" data-accessibility-name="<%= accessibility.name.downcase %>">
        <%= label_tag "accessibility_ids_#{accessibility.id}", accessibility.name %>
      </div>
      <% end %>
    </div>
    <img class="interests-child" alt="" src="/assets/Vector 5.svg">
    <div class="accessbility-issue">Accessibility</div>
    <div class="please-choose-all">Please choose all that apply.</div>
    <div class="continue-44-wrapper" id="submit-btn">
      <b class="continue-44">CONTINUE 4/4</b>
    </div>
    <div class="interests-item"></div>
    <div class="interests-inner"></div>
    <div id="selected-accessibilities"></div>
    <% end %>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      var selectedAccessibilities = new Set();
      var submitBtn = document.getElementById("submit-btn");

      function updateSubmitButtonState() {
        if (selectedAccessibilities.size > 0) {
          submitBtn.classList.add("active");
        } else {
          submitBtn.classList.remove("active");
        }
      }

      document.querySelectorAll('.wheel-chair-wrapper').forEach(function(wrapper) {
        wrapper.addEventListener('click', function() {
          var accessibilityName = this.textContent.trim();
          var accessibilityNameLower = accessibilityName.toLowerCase();

          // Check if "None" is selected or any other option
          if (accessibilityNameLower === "none") {
            // If "None" is selected, clear all other selections
            selectedAccessibilities.clear();
            document.querySelectorAll('.wheel-chair-wrapper').forEach(function(btn) {
              btn.classList.remove('selected');
            });
            selectedAccessibilities.add(accessibilityName);
            this.classList.add('selected');
          } else {
            // If another option is selected, deselect "None"
            if (selectedAccessibilities.has("None")) {
              selectedAccessibilities.delete("None");
              document.querySelector('.wheel-chair-wrapper[data-accessibility-name="none"]').classList.remove('selected');
            }
            if (selectedAccessibilities.has(accessibilityName)) {
              selectedAccessibilities.delete(accessibilityName);
              this.classList.remove('selected');
            } else {
              selectedAccessibilities.add(accessibilityName);
              this.classList.add('selected');
            }
          }
          updateSubmitButtonState();
        });
      });

      submitBtn.addEventListener("click", function(event) {
        if (submitBtn.classList.contains("active")) {
          event.preventDefault();

          fetch('http://localhost:4567/receive_data', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              user_id: <%= current_user.id %>,  // Pass user_id here
              accessibilities: Array.from(selectedAccessibilities)
            })
          })
          .then(response => response.json())
          .then(data => {
            console.log('Success:', data);
            document.querySelector("form").submit(); // Submit the form after the API call
          })
          .catch((error) => {
            console.error('Error:', error);
          });
        }
      });
    });
  </script>
</body>
</html>

app/views/profiles/setup_dietary_restrictions.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, width=device-width">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700&display=swap" />
  <style type="text/css">
    .vegetarian-wrapper {
      border-radius: 100px;
      border: 2px solid #dee0e7;
      display: inline-flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      padding: 6px 12px;
      margin: 3px;
      cursor: pointer;
      transition: background-color 0.3s, border-color 0.3s;
      font-size: 14px;
      flex: 0 0 auto;
    }
    .vegetarian-wrapper.selected {
      background-color: #ea5b6e;
      border-color: #ea5b6e;
      color: #fff;
    }
    .frame-parent {
      position: absolute;
      top: 232px;
      left: 45px;
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      align-items: flex-start;
      justify-content: flex-start;
      gap: 10px;
      height: 400px;
      overflow-y: auto;
      padding-right: 10px;
    }
    .interests-child {
      position: absolute;
      top: 66px;
      left: 29px;
      width: 9.1px;
      height: 18.1px;
    }
    .dietary-intake {
      position: absolute;
      top: 100px;
      left: 63px;
      font-size: 38.29px;
      letter-spacing: 0.04em;
      line-height: 140%;
      font-weight: 600;
      color: #010001;
    }
    .please-choose-all {
      position: absolute;
      top: 170px;
      left: 120px;
      font-size: 13.19px;
      line-height: 17.06px;
      font-weight: 500;
      color: #c6c5c7;
    }
    .continue-34-wrapper {
      position: absolute;
      top: 750px;
      left: 40px;
      border-radius: 67.18px;
      background-color: #ebecef;
      width: 312.4px;
      height: 50.4px;
      overflow: hidden;
      font-size: 18.14px;
      color: #828491;
      text-align: center;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: not-allowed; /* Initially disabled */
    }
    .continue-34-wrapper.active {
      background-color: #ff6b6b;
      color: #fff;
      cursor: pointer;
    }
    .interests-item {
      position: absolute;
      top: 46px;
      left: 0px;
      background-color: #d9d9d9;
      width: 393px;
      height: 4px;
    }
    .interests-inner {
      position: absolute;
      top: 46px;
      left: 0px;
      background-color: #ea4080;
      width: 247px;
      height: 4px;
    }
    .interests {
      width: 100%;
      position: relative;
      background-color: #fff;
      height: 852px;
      text-align: left;
      font-size: 14.98px;
      color: #bfc3cf;
      font-family: Inter;
    }
  </style>
</head>
<body>
  <div class="interests">
    <%= form_with url: update_dietary_restrictions_profile_path, method: :post do %>
    <div class="frame-parent">
      <% @dietary_restrictions.each do |restriction| %>
      <div class="vegetarian-wrapper" data-restriction-name="<%= restriction.name.downcase %>">
        <%= restriction.name %>
      </div>
      <% end %>
    </div>
    <img class="interests-child" alt="" src="/assets/Vector 5.svg">
    <div class="dietary-intake">Dietary Intake</div>
    <div class="please-choose-all">Please choose all that apply.</div>
    <div class="continue-34-wrapper" id="submit-btn">
      <b class="continue-34">CONTINUE 3/4</b>
    </div>
    <div class="interests-item"></div>
    <div class="interests-inner"></div>
    <% end %>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      var selectedRestrictions = new Set();
      var submitBtn = document.getElementById("submit-btn");

      function updateSubmitButtonState() {
        if (selectedRestrictions.size > 0) {
          submitBtn.classList.add("active");
        } else {
          submitBtn.classList.remove("active");
        }
      }

      document.querySelectorAll('.vegetarian-wrapper').forEach(function(button) {
        button.addEventListener('click', function() {
          var restrictionName = this.textContent.trim();
          var restrictionNameLower = restrictionName.toLowerCase();

          // Check if "None" is selected or any other option
          if (restrictionNameLower === "none") {
            // If "None" is selected, clear all other selections
            selectedRestrictions.clear();
            document.querySelectorAll('.vegetarian-wrapper').forEach(function(btn) {
              btn.classList.remove('selected');
            });
            selectedRestrictions.add(restrictionName);
            this.classList.add('selected');
          } else {
            // If another option is selected, deselect "None"
            if (selectedRestrictions.has("None")) {
              selectedRestrictions.delete("None");
              document.querySelector('.vegetarian-wrapper[data-restriction-name="none"]').classList.remove('selected');
            }
            if (selectedRestrictions.has(restrictionName)) {
              selectedRestrictions.delete(restrictionName);
              this.classList.remove('selected');
            } else {
              selectedRestrictions.add(restrictionName);
              this.classList.add('selected');
            }
          }
          updateSubmitButtonState();
        });
      });

      submitBtn.addEventListener("click", function(event) {
        if (selectedRestrictions.size > 0) {
          event.preventDefault();

          fetch('http://localhost:4567/receive_data', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              user_id: <%= current_user.id %>,  // Pass user_id here
              dietary_restrictions: Array.from(selectedRestrictions)
            })
          })
          .then(response => response.json())
          .then(data => {
            console.log('Success:', data);
            document.querySelector("form").submit(); // Submit the form after the API call
          })
          .catch((error) => {
            console.error('Error:', error);
          });
        } else {
          alert("Please select at least one dietary restriction.");
        }
      });
    });
  </script>
</body>
</html>

app/views/profiles/setup_hobbies.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, width=device-width">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" />
    <style type="text/css">
        .photography-wrapper {
            border-radius: 100px;
            border: 2px solid #dee0e7;
            display: inline-flex;
            flex-direction: row;
            align-items: center;
            justify-content: center;
            padding: 6px 12px;
            margin: 3px; /* Reduced margin */
            cursor: pointer;
            transition: background-color 0.3s, border-color 0.3s;
            font-size: 14px; /* Adjust font size if needed */
            flex: 0 0 auto; /* Allow flexibility for fitting in container */
        }
        .photography-wrapper.selected {
            background-color: #ea5b6e;
            border-color: #ea5b6e;
            color: #fff;
        }
        .frame-parent {
            position: absolute;
            top: 232px;
            left: 45px;
            display: flex;
            flex-direction: row;
            align-items: flex-start;
            justify-content: flex-start;
            flex-wrap: wrap;
            gap: 6px; /* Reduced gap */
            max-width: 90%; /* Adjust max-width to fit the design */
            height: 400px; /* Set a fixed height for the container */
            overflow-y: auto; /* Enable vertical scrolling */
            padding-right: 10px; /* Add some padding to the right for better appearance */
        }
        .interests-child {
            position: absolute;
            top: 66px;
            left: 29px;
            width: 9.1px;
            height: 18.1px;
        }
        .hobbies {
            position: absolute;
            top: 100px;
            left: 120px;
            font-size: 38.29px;
            letter-spacing: 0.04em;
            line-height: 140%;
            font-weight: 600;
            color: #010001;
        }
        .let-everyone-know-container {
            position: absolute;
            top: 170px;
            left: 120px;
            font-size: 13.19px;
            line-height: 17.06px;
            font-weight: 500;
            color: #c6c5c7;
        }
        .continue-24-wrapper {
            position: absolute;
            top: 750px;
            left: 40px;
            border-radius: 67.18px;
            background-color: #ebecef;
            width: 312.4px;
            height: 50.4px;
            overflow: hidden;
            font-size: 18.14px;
            color: #828491;
            text-align: center;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: not-allowed; /* Disabled initially */
        }
        .continue-24-wrapper.active {
            cursor: pointer; /* Enabled state */
            background-color: #ea5b6e;
            color: #fff;
        }
        .interests-item {
            position: absolute;
            top: 46px;
            left: 0px;
            background-color: #d9d9d9;
            width: 393px;
            height: 4px;
        }
        .interests-inner {
            position: absolute;
            top: 46px;
            left: 0px;
            background-color: #ea4080;
            width: 247px;
            height: 4px;
        }
        .interests {
            width: 100%;
            position: relative;
            background-color: #fff;
            height: 852px;
            text-align: left;
            font-size: 14.98px;
            color: #bfc3cf;
            font-family: Inter;
        }
        body {
            margin: 0;
            line-height: normal;
        }
    </style>
</head>
<body>

    <div class="interests">
        <div class="frame-parent">
            <% @hobbies.each do |hobby| %>
            <div class="photography-wrapper" data-hobby-name="<%= hobby.name %>">
                <%= hobby.name %>
            </div>
            <% end %>
        </div>
        <img class="interests-child" alt="" src="/assets/Vector 5.svg">
        <div class="hobbies">Hobbies</div>
        <div class="let-everyone-know-container">
            <p class="let-everyone-know"></p>
            <p class="let-everyone-know">Please Select 5 Hobbies </p>
        </div>
        <div class="continue-24-wrapper" id="submit-btn">
            <b class="continue-24">CONTINUE 2/4</b>
        </div>
        <div class="interests-item"></div>
        <div class="interests-inner"></div>
    </div>

    <form id="hobbies-form" action="<%= update_hobbies_profile_path %>" method="post" style="display: none;">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    </form>

    <script>
     document.addEventListener("DOMContentLoaded", function() {
        const selectedHobbies = new Set();
        const submitBtn = document.getElementById("submit-btn");

        function updateSubmitButtonState() {
            if (selectedHobbies.size >= 5) {
                submitBtn.classList.add('active');
            } else {
                submitBtn.classList.remove('active');
            }
        }

        document.querySelectorAll('.photography-wrapper').forEach(function(button) {
            button.addEventListener('click', function() {
                const hobbyName = this.getAttribute('data-hobby-name');
                if (selectedHobbies.has(hobbyName)) {
                    selectedHobbies.delete(hobbyName);
                    this.classList.remove('selected');
                } else if (selectedHobbies.size < 5) {
                    selectedHobbies.add(hobbyName);
                    this.classList.add('selected');
                } else if (selectedHobbies.size >= 5) {
                // If more than 5, do nothing or show a message (optional)
                    alert('You can only select up to 5 hobbies.');
                }
                updateSubmitButtonState();
            });
        });

        submitBtn.addEventListener('click', function(event) {
            event.preventDefault();
            if (!submitBtn.classList.contains('active')) return;

            const hobbyNames = Array.from(selectedHobbies);

            fetch('http://localhost:4567/receive_data', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ 
                user_id: <%= current_user.id %>,  // Add user_id here
                hobbies: hobbyNames 
            })
            })
            .then(response => response.json())
            .then(data => {
                console.log('Success:', data);
                document.getElementById('hobbies-form').submit();
            })
            .catch((error) => {
                console.error('Error:', error);
            });
        });
    });

</script>

</body>
</html>